name: Output Event Details on issues
on: 
  issues:
    types: [opened, edited, closed]
jobs:
  output-info:
    runs-on: ubuntu-latest
    steps:
      - name: Output issue event details
        run: echo "${{ toJSON(github.event) }}"
